[build-system]
requires = ["setuptools>=40.8.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "agent_eval_harness"
version = "0.1.0"
description = ""
requires-python = ">=3.11"
dependencies = [
    'datasets',
    'weave',
    'pydantic>=2.0.0',
    'huggingface-hub',
    'python-dotenv',
]

[tool.setuptools.packages.find]
include = ["agent_eval_harness*"]

[tool.poetry]
name = "agent-eval-harness"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]